/* inc/config.h.  Generated by configure.  */
/* inc/config.h.in.  Generated from configure.in by autoheader.  */

/* CAT_PATH */
#define CAT_PATH "/bin/cat"

/* ECHO_PATH */
#define ECHO_PATH "/bin/echo"

/* Define if IPv6 support is enabled. */
#define ENABLE_IPV6 1

/* Define if SSP C++ support is enabled. */
#define ENABLE_SSP_CXX 1

/* HAS_IOS_BINARY */
#define HAS_IOS_BINARY 1

/* HAS_IOS_NOCREATE */
/* #undef HAS_IOS_NOCREATE */

/* HAS_IOS_NOREPLACE */
/* #undef HAS_IOS_NOREPLACE */

/* HAS_SETUGID */
#define HAS_SETUGID 1

/* Define to 1 if you have the `crypt' function. */
/* #undef HAVE_CRYPT */

/* Define to 1 if you have the <crypt.h> header file. */
#define HAVE_CRYPT_H 1

/* Define to 1 if you have the `daemon' function. */
#define HAVE_DAEMON 1

/* Define to 1 if you have the `dlopen' function. */
/* #undef HAVE_DLOPEN */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `freeaddrinfo' function. */
#define HAVE_FREEADDRINFO 1

/* Define to 1 if you have the <fstream> header file. */
#define HAVE_FSTREAM 1

/* HAVE_FSTREAM_ATTACH */
/* #undef HAVE_FSTREAM_ATTACH */

/* Define to 1 if you have the `gai_strerror' function. */
#define HAVE_GAI_STRERROR 1

/* Define to 1 if you have the `getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define to 1 if you have the `getgrnam' function. */
#define HAVE_GETGRNAM 1

/* Define to 1 if you have the `getnameinfo' function. */
#define HAVE_GETNAMEINFO 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the `getpid' function. */
#define HAVE_GETPID 1

/* Define to 1 if you have the `getpwnam' function. */
#define HAVE_GETPWNAM 1

/* Define to 1 if you have the <grp.h> header file. */
#define HAVE_GRP_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iomanip> header file. */
#define HAVE_IOMANIP 1

/* Define to 1 if you have the <iostream> header file. */
#define HAVE_IOSTREAM 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `xml' library (-lxml). */
#define HAVE_LIBXML 1

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* HAVE_MKSTEMP */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the <netinet/in_systm.h> header file. */
#define HAVE_NETINET_IN_SYSTM_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define HAVE_NETINET_TCP_H 1

/* Define to 1 if you have the <ostream> header file. */
#define HAVE_OSTREAM 1

/* Define to 1 if you have the <ostream.h> header file. */
#define HAVE_OSTREAM_H 1

/* Define to 1 if you have the <parser.h> header file. */
#define HAVE_PARSER_H 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define to 1 if you have the `setgid' function. */
#define HAVE_SETGID 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* Define to 1 if you have the `setuid' function. */
#define HAVE_SETUID 1

/* Define to 1 if you have the `snprintf' function. */
#define HAVE_SNPRINTF 1

/* HAVE_SNPRINTF_T */
#define HAVE_SNPRINTF_T 1

/* Define if struct sockaddr_in6 has the sin6_scope_id member */
#define HAVE_SOCKADDR_IN6_SCOPE_ID 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strncasecmp' function. */
#define HAVE_STRNCASECMP 1

/* Define to 1 if you have the `strsep' function. */
#define HAVE_STRSEP 1

/* Define to 1 if the system has the type `struct sockaddr_in6'. */
#define HAVE_STRUCT_SOCKADDR_IN6 1

/* Define to 1 if you have the <sys/bitypes.h> header file. */
#define HAVE_SYS_BITYPES_H 1

/* Define to 1 if you have the <sys/inttypes.h> header file. */
/* #undef HAVE_SYS_INTTYPES_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* HAVE_TIOCNOTTY */
#define HAVE_TIOCNOTTY 1

/* Define to 1 if you have the `truncate' function. */
#define HAVE_TRUNCATE 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* HAVE_VSNPRINTF_T */
#define HAVE_VSNPRINTF_T 1

/* Define to 1 if you have the `xmlKeepBlanksDefault' function. */
#define HAVE_XMLKEEPBLANKSDEFAULT 1

/* Define to 1 if you have the <xmlmemory.h> header file. */
#define HAVE_XMLMEMORY_H 1

/* HOST */
#define HOST "x86_64-unknown-linux-gnu"

/* MBOT_CRYPT */
#define MBOT_CRYPT 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* PERL_PATH */
#define PERL_PATH "/usr/bin/perl"

/* PING_PATH */
#define PING_PATH "/bin/ping"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* SENDMAIL_PATH */
#define SENDMAIL_PATH "/usr/sbin/sendmail"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* VERSION */
#define VERSION "5.2.0"

/* VERSION_STRING */
#define VERSION_STRING "mirage irc bot 5.2.0"

/* WHOIS_PATH */
#define WHOIS_PATH "/usr/bin/whois"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* socklen_t */
/* #undef socklen_t */

/* Define to `unsigned char' if <sys/types.h> does not define. */
/* #undef u_char */

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef u_int */

/* Define to `unsigned long' if <sys/types.h> does not define. */
/* #undef u_long */

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef u_short */

/* uint32_t */
/* #undef uint32_t */

/* uint_fast32_t */
/* #undef uint_fast32_t */
